//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketCustomer.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public int customerId { get; set; }
        public string customerFirstName { get; set; }
        public string customerLastName { get; set; }
        public string customerPhoneNumber { get; set; }
        public string customerAddress { get; set; }
        public Nullable<decimal> customerDebt { get; set; }
    }
}
